use_frameworks!

platform :ios, '9.0'

target 'NewDemoViewModelProtocol_Example' do
  pod 'NewDemoViewModelProtocol', :path => '../'

  target 'NewDemoViewModelProtocol_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
